services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://localhost:3001
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - transcendence-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
      - "4001-4010:4001-4010"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./data:/usr/src/app/data
    env_file:
      - ./.env
    networks:
      - transcendence-net

  pong-server:
    build:
      context: ./pong-server
      dockerfile: Dockerfile
    command: ["./netpong_server", "0.0.0.0", "4000"]
    ports:
      - "4000:4000"
    expose:
      - "4000"
      - "4001-4010"
    networks:
      - transcendence-net

networks:
  transcendence-net:
    driver: bridge